// Auto-generated by scripts/generate-warmup-audio.mjs — do not edit manually.
// Regenerate: ELEVENLABS_API_KEY=sk-... node scripts/generate-warmup-audio.mjs

import type { AudioWordTiming } from "./narration-timer";

/** Word-level timing for the warmup vignette narration (narrative + 3 prompts). */
export const WARMUP_AUDIO_TIMING: AudioWordTiming[] = [
  {
    "word": "Every",
    "start": 0,
    "end": 0.325,
    "section": "narrative"
  },
  {
    "word": "great",
    "start": 0.383,
    "end": 0.604,
    "section": "narrative"
  },
  {
    "word": "company",
    "start": 0.662,
    "end": 0.998,
    "section": "narrative"
  },
  {
    "word": "started",
    "start": 1.091,
    "end": 1.556,
    "section": "narrative"
  },
  {
    "word": "with",
    "start": 1.765,
    "end": 1.962,
    "section": "narrative"
  },
  {
    "word": "someone",
    "start": 2.02,
    "end": 2.38,
    "section": "narrative"
  },
  {
    "word": "noticing",
    "start": 2.438,
    "end": 2.844,
    "section": "narrative"
  },
  {
    "word": "something",
    "start": 2.914,
    "end": 3.262,
    "section": "narrative"
  },
  {
    "word": "others",
    "start": 3.437,
    "end": 3.773,
    "section": "narrative"
  },
  {
    "word": "missed.",
    "start": 3.866,
    "end": 4.423,
    "section": "narrative"
  },
  {
    "word": "A",
    "start": 4.934,
    "end": 5.004,
    "section": "narrative"
  },
  {
    "word": "frustration",
    "start": 5.074,
    "end": 5.84,
    "section": "narrative"
  },
  {
    "word": "that",
    "start": 6.049,
    "end": 6.246,
    "section": "narrative"
  },
  {
    "word": "everyone",
    "start": 6.362,
    "end": 6.827,
    "section": "narrative"
  },
  {
    "word": "else",
    "start": 6.873,
    "end": 7.094,
    "section": "narrative"
  },
  {
    "word": "accepted.",
    "start": 7.129,
    "end": 7.779,
    "section": "narrative"
  },
  {
    "word": "A",
    "start": 8.22,
    "end": 8.313,
    "section": "narrative"
  },
  {
    "word": "gap",
    "start": 8.429,
    "end": 8.824,
    "section": "narrative"
  },
  {
    "word": "that",
    "start": 8.998,
    "end": 9.218,
    "section": "narrative"
  },
  {
    "word": "nobody",
    "start": 9.346,
    "end": 9.729,
    "section": "narrative"
  },
  {
    "word": "thought",
    "start": 9.787,
    "end": 10.019,
    "section": "narrative"
  },
  {
    "word": "to",
    "start": 10.066,
    "end": 10.136,
    "section": "narrative"
  },
  {
    "word": "fill.",
    "start": 10.252,
    "end": 10.786,
    "section": "narrative"
  },
  {
    "word": "The",
    "start": 11.389,
    "end": 11.517,
    "section": "narrative"
  },
  {
    "word": "founders",
    "start": 11.61,
    "end": 12.04,
    "section": "narrative"
  },
  {
    "word": "who",
    "start": 12.074,
    "end": 12.202,
    "section": "narrative"
  },
  {
    "word": "built",
    "start": 12.283,
    "end": 12.516,
    "section": "narrative"
  },
  {
    "word": "the",
    "start": 12.55,
    "end": 12.62,
    "section": "narrative"
  },
  {
    "word": "companies",
    "start": 12.666,
    "end": 13.061,
    "section": "narrative"
  },
  {
    "word": "you",
    "start": 13.119,
    "end": 13.212,
    "section": "narrative"
  },
  {
    "word": "use",
    "start": 13.328,
    "end": 13.607,
    "section": "narrative"
  },
  {
    "word": "every",
    "start": 13.688,
    "end": 13.978,
    "section": "narrative"
  },
  {
    "word": "day",
    "start": 14.048,
    "end": 14.35,
    "section": "narrative"
  },
  {
    "word": "weren't",
    "start": 14.675,
    "end": 14.988,
    "section": "narrative"
  },
  {
    "word": "born",
    "start": 15.047,
    "end": 15.337,
    "section": "narrative"
  },
  {
    "word": "with",
    "start": 15.383,
    "end": 15.511,
    "section": "narrative"
  },
  {
    "word": "some",
    "start": 15.546,
    "end": 15.743,
    "section": "narrative"
  },
  {
    "word": "special",
    "start": 15.79,
    "end": 16.161,
    "section": "narrative"
  },
  {
    "word": "gene",
    "start": 16.231,
    "end": 16.475,
    "section": "narrative"
  },
  {
    "word": "for",
    "start": 16.509,
    "end": 16.614,
    "section": "narrative"
  },
  {
    "word": "business",
    "start": 16.672,
    "end": 17.136,
    "section": "narrative"
  },
  {
    "word": "—",
    "start": 17.415,
    "end": 17.461,
    "section": "narrative"
  },
  {
    "word": "they",
    "start": 17.972,
    "end": 18.135,
    "section": "narrative"
  },
  {
    "word": "just",
    "start": 18.228,
    "end": 18.448,
    "section": "narrative"
  },
  {
    "word": "paid",
    "start": 18.506,
    "end": 18.704,
    "section": "narrative"
  },
  {
    "word": "attention",
    "start": 18.739,
    "end": 19.122,
    "section": "narrative"
  },
  {
    "word": "differently.",
    "start": 19.191,
    "end": 19.83,
    "section": "narrative"
  },
  {
    "word": "They",
    "start": 20.434,
    "end": 20.608,
    "section": "narrative"
  },
  {
    "word": "asked",
    "start": 20.677,
    "end": 21.014,
    "section": "narrative"
  },
  {
    "word": "\"why",
    "start": 21.188,
    "end": 21.537,
    "section": "narrative"
  },
  {
    "word": "does",
    "start": 21.583,
    "end": 21.699,
    "section": "narrative"
  },
  {
    "word": "it",
    "start": 21.734,
    "end": 21.804,
    "section": "narrative"
  },
  {
    "word": "have",
    "start": 21.862,
    "end": 22.024,
    "section": "narrative"
  },
  {
    "word": "to",
    "start": 22.059,
    "end": 22.105,
    "section": "narrative"
  },
  {
    "word": "be",
    "start": 22.175,
    "end": 22.291,
    "section": "narrative"
  },
  {
    "word": "this",
    "start": 22.349,
    "end": 22.489,
    "section": "narrative"
  },
  {
    "word": "way?\"",
    "start": 22.558,
    "end": 22.988,
    "section": "narrative"
  },
  {
    "word": "when",
    "start": 23.592,
    "end": 23.789,
    "section": "narrative"
  },
  {
    "word": "everyone",
    "start": 23.87,
    "end": 24.277,
    "section": "narrative"
  },
  {
    "word": "else",
    "start": 24.311,
    "end": 24.486,
    "section": "narrative"
  },
  {
    "word": "asked",
    "start": 24.532,
    "end": 24.845,
    "section": "narrative"
  },
  {
    "word": "\"where",
    "start": 25.054,
    "end": 25.716,
    "section": "narrative"
  },
  {
    "word": "do",
    "start": 25.739,
    "end": 25.797,
    "section": "narrative"
  },
  {
    "word": "I",
    "start": 25.879,
    "end": 25.902,
    "section": "narrative"
  },
  {
    "word": "sign",
    "start": 25.983,
    "end": 26.204,
    "section": "narrative"
  },
  {
    "word": "up?\"",
    "start": 26.273,
    "end": 26.645,
    "section": "narrative"
  },
  {
    "word": "Today,",
    "start": 27.342,
    "end": 28.05,
    "section": "narrative"
  },
  {
    "word": "you're",
    "start": 28.259,
    "end": 28.456,
    "section": "narrative"
  },
  {
    "word": "going",
    "start": 28.479,
    "end": 28.642,
    "section": "narrative"
  },
  {
    "word": "to",
    "start": 28.688,
    "end": 28.735,
    "section": "narrative"
  },
  {
    "word": "practice",
    "start": 28.793,
    "end": 29.188,
    "section": "narrative"
  },
  {
    "word": "thinking",
    "start": 29.222,
    "end": 29.536,
    "section": "narrative"
  },
  {
    "word": "like",
    "start": 29.594,
    "end": 29.756,
    "section": "narrative"
  },
  {
    "word": "they",
    "start": 29.791,
    "end": 29.942,
    "section": "narrative"
  },
  {
    "word": "do.",
    "start": 30.012,
    "end": 30.407,
    "section": "narrative"
  },
  {
    "word": "You'll",
    "start": 31.01,
    "end": 31.243,
    "section": "narrative"
  },
  {
    "word": "hear",
    "start": 31.301,
    "end": 31.452,
    "section": "narrative"
  },
  {
    "word": "a",
    "start": 31.498,
    "end": 31.533,
    "section": "narrative"
  },
  {
    "word": "short",
    "start": 31.58,
    "end": 31.788,
    "section": "narrative"
  },
  {
    "word": "scenario,",
    "start": 31.835,
    "end": 32.59,
    "section": "narrative"
  },
  {
    "word": "then",
    "start": 32.915,
    "end": 33.205,
    "section": "narrative"
  },
  {
    "word": "answer",
    "start": 33.379,
    "end": 33.704,
    "section": "narrative"
  },
  {
    "word": "three",
    "start": 33.762,
    "end": 33.971,
    "section": "narrative"
  },
  {
    "word": "questions",
    "start": 34.006,
    "end": 34.424,
    "section": "narrative"
  },
  {
    "word": "about",
    "start": 34.459,
    "end": 34.691,
    "section": "narrative"
  },
  {
    "word": "it.",
    "start": 34.737,
    "end": 35.063,
    "section": "narrative"
  },
  {
    "word": "There",
    "start": 35.504,
    "end": 35.724,
    "section": "narrative"
  },
  {
    "word": "are",
    "start": 35.759,
    "end": 35.875,
    "section": "narrative"
  },
  {
    "word": "no",
    "start": 35.933,
    "end": 36.096,
    "section": "narrative"
  },
  {
    "word": "wrong",
    "start": 36.154,
    "end": 36.409,
    "section": "narrative"
  },
  {
    "word": "answers",
    "start": 36.479,
    "end": 36.932,
    "section": "narrative"
  },
  {
    "word": "—",
    "start": 37.141,
    "end": 37.187,
    "section": "narrative"
  },
  {
    "word": "we're",
    "start": 37.628,
    "end": 37.872,
    "section": "narrative"
  },
  {
    "word": "just",
    "start": 37.907,
    "end": 38.069,
    "section": "narrative"
  },
  {
    "word": "interested",
    "start": 38.128,
    "end": 38.592,
    "section": "narrative"
  },
  {
    "word": "in",
    "start": 38.708,
    "end": 38.847,
    "section": "narrative"
  },
  {
    "word": "how",
    "start": 38.929,
    "end": 39.068,
    "section": "narrative"
  },
  {
    "word": "you",
    "start": 39.184,
    "end": 39.312,
    "section": "narrative"
  },
  {
    "word": "think.",
    "start": 39.428,
    "end": 39.939,
    "section": "narrative"
  },
  {
    "word": "...",
    "start": 39.962,
    "end": 40.055,
    "section": "phase_1_prompt"
  },
  {
    "word": "What's",
    "start": 40.867,
    "end": 41.135,
    "section": "phase_1_prompt"
  },
  {
    "word": "something",
    "start": 41.181,
    "end": 41.483,
    "section": "phase_1_prompt"
  },
  {
    "word": "you've",
    "start": 41.529,
    "end": 41.727,
    "section": "phase_1_prompt"
  },
  {
    "word": "built",
    "start": 41.761,
    "end": 42.052,
    "section": "phase_1_prompt"
  },
  {
    "word": "or",
    "start": 42.168,
    "end": 42.319,
    "section": "phase_1_prompt"
  },
  {
    "word": "created",
    "start": 42.388,
    "end": 42.899,
    "section": "phase_1_prompt"
  },
  {
    "word": "that",
    "start": 43.073,
    "end": 43.236,
    "section": "phase_1_prompt"
  },
  {
    "word": "you're",
    "start": 43.271,
    "end": 43.433,
    "section": "phase_1_prompt"
  },
  {
    "word": "proud",
    "start": 43.457,
    "end": 43.724,
    "section": "phase_1_prompt"
  },
  {
    "word": "of?",
    "start": 43.77,
    "end": 44.118,
    "section": "phase_1_prompt"
  },
  {
    "word": "...",
    "start": 44.165,
    "end": 44.292,
    "section": "phase_2_prompt"
  },
  {
    "word": "If",
    "start": 45.105,
    "end": 45.244,
    "section": "phase_2_prompt"
  },
  {
    "word": "you",
    "start": 45.291,
    "end": 45.361,
    "section": "phase_2_prompt"
  },
  {
    "word": "could",
    "start": 45.419,
    "end": 45.558,
    "section": "phase_2_prompt"
  },
  {
    "word": "start",
    "start": 45.593,
    "end": 45.848,
    "section": "phase_2_prompt"
  },
  {
    "word": "any",
    "start": 45.918,
    "end": 46.115,
    "section": "phase_2_prompt"
  },
  {
    "word": "business",
    "start": 46.185,
    "end": 46.545,
    "section": "phase_2_prompt"
  },
  {
    "word": "tomorrow,",
    "start": 46.579,
    "end": 47.206,
    "section": "phase_2_prompt"
  },
  {
    "word": "what",
    "start": 47.81,
    "end": 47.984,
    "section": "phase_2_prompt"
  },
  {
    "word": "would",
    "start": 48.019,
    "end": 48.158,
    "section": "phase_2_prompt"
  },
  {
    "word": "it",
    "start": 48.205,
    "end": 48.263,
    "section": "phase_2_prompt"
  },
  {
    "word": "be?",
    "start": 48.309,
    "end": 48.634,
    "section": "phase_2_prompt"
  },
  {
    "word": "...",
    "start": 48.658,
    "end": 48.739,
    "section": "phase_3_prompt"
  },
  {
    "word": "What's",
    "start": 49.552,
    "end": 49.819,
    "section": "phase_3_prompt"
  },
  {
    "word": "one",
    "start": 49.911,
    "end": 50.155,
    "section": "phase_3_prompt"
  },
  {
    "word": "thing",
    "start": 50.19,
    "end": 50.376,
    "section": "phase_3_prompt"
  },
  {
    "word": "about",
    "start": 50.422,
    "end": 50.655,
    "section": "phase_3_prompt"
  },
  {
    "word": "you",
    "start": 50.724,
    "end": 50.875,
    "section": "phase_3_prompt"
  },
  {
    "word": "that",
    "start": 51.119,
    "end": 51.305,
    "section": "phase_3_prompt"
  },
  {
    "word": "most",
    "start": 51.398,
    "end": 51.653,
    "section": "phase_3_prompt"
  },
  {
    "word": "people",
    "start": 51.699,
    "end": 52.001,
    "section": "phase_3_prompt"
  },
  {
    "word": "wouldn't",
    "start": 52.036,
    "end": 52.303,
    "section": "phase_3_prompt"
  },
  {
    "word": "guess?",
    "start": 52.35,
    "end": 53.035,
    "section": "phase_3_prompt"
  }
];

/** Total audio duration in seconds. */
export const WARMUP_AUDIO_DURATION = 53.035;
